export const LOAGIN_USER = 'LOGIN_USER';
export const LOAGIN_USER_FAILED = 'LOAGIN_USER_FAILED';
export const LOAGIN_USER_SUCCESS = 'LOAGIN_USER_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
