export const GET_REPOS = 'GET_REPOS';
export const GET_REPOS_FAILED = 'GET_REPOS_FAILED';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';

export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SEARCH_REPOS_FAILED = 'SEARCH_REPOS_FAILED';
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS';
